### PR TITLE
support for DBAAS

### PR DESCRIPTION
**Pull request by tahsin352**
support for DBAAS

### CODE REVIEW

**Comment by andyjeffries** [comment]
Think we're missing quite a few endpoints...

```
    post :create, "/v#{ENV["CIVO_API_VERSION"] || "2"}/databases", requires: [:name, :size, :region]
    put :tags, "/v2/databases/:id/tags"
    put :update, "/v2/databases/:id"
    delete :remove, "/v#{ENV["CIVO_API_VERSION"] || "2"}/databases/:id", requires: [:id], send_delete_body: true
    put :upgrade, "/v#{ENV["CIVO_API_VERSION"] || "2"}/databases/:id/resize", requires: [:size, :id]
```

**Comment by andyjeffries** [comment]
Also as we'll be supporting restoring back to a previous automated snapshot of the database, I guess there should be:

```
get :snapshots, "/v2/databases/:id/snapshots"
put :restore, "/v2/databases/:id/restore", requires: [:snapshot_id]
```

**Comment by tahsin352** [comment]
> Also as we'll be supporting restoring back to a previous automated snapshot of the database, I guess there should be:
> 
> ```
> get :snapshots, "/v2/databases/:id/snapshots"
> put :restore, "/v2/databases/:id/restore", requires: [:snapshot_id]
> ```

Do we need create snapshots?

**Comment by andyjeffries** [comment]
> Do we need create snapshots?

Unsure to be honest, I think we may just go with automatic snapshots at first (and we may not even launch with those, depending on how well they work and how much space they take).

**Comment by tahsin352** [comment]
Do we need `start`, `stop`, `status` endpoint?

**Comment by andyjeffries** [comment]
I don't think we need start/stop, not planning on allowing that. Status I think would just be part of the DBAAS object itself, connect likewise, just part of the DatabaseSerializer. Stats let's not worry about for now, I don't know what stats we can provide and we're looking at a v1 release, so let's not go crazy.

**Comment by andyjeffries** [comment]
Released to Rubygems.

**Pull request merged**
